### ISSUE TITLE
use_2to3 is not supported by setuptools > v58 and causes package to fail install

### ISSUE THREAD

**Issue by ascherer97** [pyoceans/python-airsea#10]
First, I know this project has not been worked on for some time, but I still find some use for it. Thanks for putting it together. 

When updating new environments with this package, install has failed unless I use old pip versions since use_2to3 in setup.py is no longer supported in setuptools >=v58 (see [here](https://setuptools.pypa.io/en/latest/history.html#v58-0-0)). Simply removing it seems to have no ill effects on this code when I tested and fixes the install issue, but I admit there may be some reason for including it that I am unaware of, so in this case feel free to close/ignore this issue.

**Comment by ocefpaf** [comment]
I'm not planning on maintaining it, sorry. But I'd be happy to hand it over to you if you want to.

However, before you jump into that rabbit hole, please check if https://github.com/xgcm/aerobulk-python does what you need. That one will probably be better maintained in the long run.

**Comment by ascherer97** [comment]
No problem, thanks for the reply! I appreciate the tip on AeroBulk - looks like a useful package. I'd be willing to try and maintain this, too, just let me know.

**Comment by tompc35** [comment]
I'd be willing  to work on maintaining this package and adding some tests (comparisons with the original Matlab toolbox) as well.

**Comment by ocefpaf** [comment]
@tompc35 tag, you are it :-)

The invitation to maintainer rights to this repo should be on your email. I can help with boilerplate packaging and publishing stuff, but I don't have the bandwidth to deal with updating the code.
