### ISSUE TITLE
air_dens gives different answer from example?

### ISSUE THREAD

**Issue by tompc35** [pyoceans/python-airsea#8]
First of all, thank you for contributing this very useful package.

I am having an issue computing air density. I follow the example in the help:

> from airsea import atmosphere as asea
> asea.air_dens([5., 15., 23.1], 95.)

which gives the output:

> array([ 0.31680206,  0.17759143,  0.11009906])

instead of the correct output shown in the help:

> array([ 1.27361105,  1.22578105,  1.18750778])

I think the issue may have to do with the qsat function. Comparing the Matlab and Python code, there is a factor of 100 difference in the q calculation.

**Comment by ocefpaf** [comment]
Hi @tompc35,  thanks for the report.  Every-time someone gives me some feedback on `python-airsea` I am a little bit embarrassed :flushed:

I started this project a long time ago, but never got time to finish it.  That is why I do not recommend you to use it unless you are certain of what you are doing!

I will try to take a look into this, but it is unlikely I will have any free cycles in the next month or so.

PS: If you want to send a PR it would be awesome :wink:

**Comment by tompc35** [comment]
Thanks again for getting the project going. I sent a pull request.

**Comment by ocefpaf** [comment]
Clsoed by #9
